export type ArtworkType =
  | 'error-mobile'
  | 'network'
  | 'no-chart-boxed'
  | 'no-chart'
  | 'no-data-boxed'
  | 'no-data'
  | 'no-image-boxed'
  | 'no-image'
  | 'warn-api'
  | 'warn-auth'
  | 'warn-generic'
  | 'warn-server'
  | 'warn-sync'
  | 'warn-ui'
  | 'working-animated'
  | 'working';
