version: 1
update_configs:
  # marketing-cloud-logo
  - package_manager: 'javascript'
    directory: '/packages/marketing-cloud-logo'
    update_schedule: 'weekly'
    default_labels:
      - 'marketing-cloud-logo'
      - 'dependencies'

  # design-tokens
  - package_manager: 'javascript'
    directory: '/packages/design-tokens'
    update_schedule: 'weekly'
    default_labels:
      - 'design-tokens'
      - 'dependencies'

  # emails
  - package_manager: 'javascript'
    directory: '/packages/emails'
    update_schedule: 'weekly'
    default_labels:
      - 'emails'
      - 'dependencies'

  # service-pages
  - package_manager: 'javascript'
    directory: '/packages/service-pages'
    update_schedule: 'weekly'
    default_labels:
      - 'service-pages'
      - 'dependencies'
