/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import {HTMLStencilElement, JSXBase} from '@stencil/core/internal';
import {FillColor, FillStyle, Size, Type} from './typings/props';
export namespace Components {
  interface ClabLogo {
    compact: boolean;
    fillColor: FillColor;
    fillStyle: FillStyle;
    size: Size;
    type: Type;
  }
  interface ClabLogotype {
    compact: boolean;
    fillColor: FillColor;
    size: Size;
    type: Type;
  }
  interface ClabPictogram {
    fillColor: FillColor;
    size: Size;
  }
}
declare global {
  interface HTMLClabLogoElement
    extends Components.ClabLogo,
      HTMLStencilElement {}
  var HTMLClabLogoElement: {
    prototype: HTMLClabLogoElement;
    new (): HTMLClabLogoElement;
  };
  interface HTMLClabLogotypeElement
    extends Components.ClabLogotype,
      HTMLStencilElement {}
  var HTMLClabLogotypeElement: {
    prototype: HTMLClabLogotypeElement;
    new (): HTMLClabLogotypeElement;
  };
  interface HTMLClabPictogramElement
    extends Components.ClabPictogram,
      HTMLStencilElement {}
  var HTMLClabPictogramElement: {
    prototype: HTMLClabPictogramElement;
    new (): HTMLClabPictogramElement;
  };
  interface HTMLElementTagNameMap {
    'clab-logo': HTMLClabLogoElement;
    'clab-logotype': HTMLClabLogotypeElement;
    'clab-pictogram': HTMLClabPictogramElement;
  }
}
declare namespace LocalJSX {
  interface ClabLogo {
    compact?: boolean;
    fillColor?: FillColor;
    fillStyle?: FillStyle;
    size?: Size;
    type?: Type;
  }
  interface ClabLogotype {
    compact?: boolean;
    fillColor?: FillColor;
    size?: Size;
    type?: Type;
  }
  interface ClabPictogram {
    fillColor?: FillColor;
    size?: Size;
  }
  interface IntrinsicElements {
    'clab-logo': ClabLogo;
    'clab-logotype': ClabLogotype;
    'clab-pictogram': ClabPictogram;
  }
}
export {LocalJSX as JSX};
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'clab-logo': LocalJSX.ClabLogo &
        JSXBase.HTMLAttributes<HTMLClabLogoElement>;
      'clab-logotype': LocalJSX.ClabLogotype &
        JSXBase.HTMLAttributes<HTMLClabLogotypeElement>;
      'clab-pictogram': LocalJSX.ClabPictogram &
        JSXBase.HTMLAttributes<HTMLClabPictogramElement>;
    }
  }
}
